In [1]:
"""
FINAL ALIGNMENT SCRIPT: Hausa Mini-LLM GRPO
Optimized for: Tesla T4 (15GB VRAM)
Paper: "Efficient Alignment of Mini-LLMs for Hausa Language using GRPO and Unsloth"
"""

# ==============================================================================
# 0. INSTALL DEPENDENCIES (Required for Google Colab)
# ==============================================================================
import os

# Check if unsloth is installed; if not, install the necessary stack
try:
    import unsloth
except ImportError:
    print("Installing Unsloth and training dependencies...")
    # These specific versions and flags ensure compatibility with the Tesla T4
    os.system("pip install --quiet unsloth")
    os.system("pip install --quiet --no-deps trl peft accelerate bitsandbytes")
    os.system("pip install --quiet xformers")
    print("Installation complete. Proceeding to model initialization.")

import torch
from unsloth import FastLanguageModel, is_bfloat16_supported
from trl import GRPOTrainer, GRPOConfig
from datasets import Dataset
import re

# ==============================================================================
# 1. MODEL & PEFT INITIALIZATION (Section 2.1)
# ==============================================================================
model_name = "unsloth/Llama-3.2-3B-Instruct"
max_seq_length = 1024

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_seq_length,
    load_in_4bit = True,
    fast_inference = False, # Stability for T4
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # From Appendix A
    lora_alpha = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"], # MLP included
    lora_dropout = 0,
    bias = "none",
)

# ==============================================================================
# 2. DATASET PREPARATION (The Alignment Corpus)
# ==============================================================================
hausa_data = [
    {"prompt": "Bayyana yadda ake yin tuwon shinkafa."},
    {"prompt": "Yaya ake girka miyar kuka dalla-dalla?"},
    {"prompt": "Yaya ya kamata a gaishe da dattijo a kasar Hausa?"},
    {"prompt": "Bani tarihin birnin Kano a takaice."},
    {"prompt": "Wace hanya ce mafi kyau ta wanke danyen kifi?"},
    {"prompt": "Wane ne sarkin Musulmi kuma ina fada take?"},
    {"prompt": "Idan bako ya zo gidanka, yaya kake karbarsa?"}
]
dataset = Dataset.from_list(hausa_data)

# ==============================================================================
# 3. REWARD FUNCTIONS (The GRPO Engine)
# ==============================================================================

def hausa_syntax_reward(prompts, completions, **kwargs):
    """
    Rewards completions using procedural Hausa markers (farko, sannan, wanke).
    Targets the 121% increase in syntactic coherence.
    """
    keywords = ["farko", "sannan", "kuma", "zuba", "wanke", "ruwa", "karshe"]
    rewards = []
    for completion in completions:
        # Check for density of Hausa function words
        count = sum(1 for word in keywords if word in completion.lower())
        rewards.append(1.0 if count >= 3 else 0.0)
    return rewards

def swahili_drift_penalty(prompts, completions, **kwargs):
    """
    Penalizes Swahili 'attractor' words (pika, katika, sana) identified in Table 2.
    Ensures cultural and linguistic anchoring.
    """
    swahili_indicators = ["pika", "katika", "habari", "sana", "nzuri", "kwanza"]
    rewards = []
    for completion in completions:
        found_drift = any(word in completion.lower() for word in swahili_indicators)
        rewards.append(-1.5 if found_drift else 0.5)
    return rewards

def repetition_penalty(prompts, completions, **kwargs):
    """
    Mitigates 'Linguistic Shadowing' (looping behavior).
    Calculates unique word ratio (U).
    """
    rewards = []
    for completion in completions:
        words = completion.split()
        if len(words) == 0:
            rewards.append(-1.0)
            continue
        u_ratio = len(set(words)) / len(words)
        # Threshold from paper: U >= 0.6 is good
        rewards.append(1.0 if u_ratio >= 0.6 else -1.0)
    return rewards

# ==============================================================================
# 4. TRAINING CONFIGURATION (Appendix A)
# ==============================================================================
training_args = GRPOConfig(
    output_dir = "hausa-llama-3b-grpo",
    learning_rate = 5e-6,      # From Table 2
    beta = 0.01,              # KL Coefficient
    num_generations = 8,       # Group Size G=8
    max_prompt_length = 256,
    max_completion_length = 512,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 4,
    max_steps = 20,            # Mini-run for validation
    logging_steps = 1,
    fp16 = not is_bfloat16_supported(),
    bf16 = is_bfloat16_supported(),
    optim = "adamw_8bit",      # Memory efficiency for T4
)

trainer = GRPOTrainer(
    model = model,
    reward_funcs = [hausa_syntax_reward, swahili_drift_penalty, repetition_penalty],
    args = training_args,
    train_dataset = dataset,
)

# ==============================================================================
# 5. EXECUTION & INFERENCE TEST
# ==============================================================================
print("\n[STEP 1] Starting GRPO Alignment...")
trainer.train()

print("\n[STEP 2] Testing Aligned Output (Anchoring Test)...")
FastLanguageModel.for_inference(model)

test_prompt = "Bayyana yadda ake yin tuwon shinkafa."
inputs = tokenizer.apply_chat_template(
    [{"role": "user", "content": test_prompt}],
    add_generation_prompt = True,
    return_tensors = "pt"
).to("cuda")

outputs = model.generate(
    input_ids = inputs,
    max_new_tokens = 128,
    temperature = 0.7,
    pad_token_id = tokenizer.eos_token_id
)

print("\nALIGNED RESPONSE:")
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# 6. Save final adapters
model.save_pretrained_merged("hausa_aligned_final", tokenizer, save_method = "lora")
print("\n✅ Alignment Complete. Model saved as 'hausa_aligned_final'")

Installing Unsloth and training dependencies...
Installation complete. Proceeding to model initialization.
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.4: Fast Llama patching. Transformers: 5.2.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.35G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth: Will load unsloth/llama-3.2-3b-instruct-unsloth-bnb-4bit as a legacy tokenizer.
Unsloth 2026.3.4 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 8

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

[STEP 1] Starting GRPO Alignment...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7 | Num Epochs = 20 | Total steps = 20
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 4 x 1) = 32
 "-____-"     Trainable parameters = 24,313,856 of 3,237,063,680 (0.75% trained)
Passing `generation_config` together with generation-related arguments=({'disable_compile', 'cache_implementation', 'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    ColabKernelApp.launch_instance()
  File "/usr/local/lib/python3.12/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.12/dist-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "/usr/local/lib/python3.12/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/local/lib/python3.12/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1523/2797928060.py", line 141, in <cell line: 0>
    trainer.train()
  File "/content/unsloth_compiled_cache/UnslothGRPOTrainer.py", line 68, in wrapper
    output = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 1412, in train
    return inner_training_loop(
  File "<string>", line 332, in _fast_inner_training_loop
  File "<string>", line 34, in _unsloth_training_step
  File "/usr/local/lib/python3.12/dist-packages/trl/extras/profiling.py", line 98, in wrapper
    return func(self, *args, **kwargs)
  File "/content/unsloth_compiled_cache/UnslothGRPOTrainer.py", line 2725, in _prepare_inputs
    generation_batch = self._generate_and_score_completions(generation_batch)
  File "/usr/local/lib/python3.12/dist-packages/unsloth/models/rl.py", line 450, in wrapped
    return original(self, *args, **kwargs)
  File "/content/unsloth_compiled_cache/UnslothGRPOTrainer.py", line 3125, in _generate_and_score_completions
    ) = self._generate(prompts, images)
  File "/content/unsloth_compiled_cache/UnslothGRPOTrainer.py", line 3056, in _generate
    prompt_ids, completion_ids, logprobs, forward_kwargs = self._generate_single_turn(prompts, images)
  File "/content/unsloth_compiled_cache/UnslothGRPOTrainer.py", line 3032, in _generate_single_turn
    prompt_completion_ids = unwrapped_model.generate(
  File "/usr/local/lib/python3.12/dist-packages/unsloth/models/rl.py", line 144, in generate_with_clone
    out = original_generate(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/peft/peft_model.py", line 2048, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/unsloth/models/llama.py", line 2128, in unsloth_fast_generate
    output = self._old_generate(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py", line 2668, in generate
    result = decoding_method(
  File "/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py", line 2863, in _sample
    outputs = self._prefill(input_ids, generation_config, model_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py", line 3857, in _prefill
    return self(**model_inputs, return_dict=True)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/unsloth/models/llama.py", line 1474, in _CausalLM_fast_forward
    outputs = self.model(
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/unsloth/models/llama.py", line 1058, in LlamaModel_fast_forward
    attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py", line 394, in _prepare_4d_causal_attention_mask_for_sdpa
    attn_mask_converter = AttentionMaskConverter(is_causal=True, sliding_window=sliding_window)
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py", line 74, in __init__
    logger.warning_once(DEPRECATION_MESSAGE, FutureWarning)
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/logging.py", line 327, in warning_once
    self.warning(*args, **kwargs)
Message: 'The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.'
Arguments: (<class 'FutureWarning'>,)

[STEP 2] Testing Aligned Output (Anchoring Test)...

ALIGNED RESPONSE:
system

Cutting Knowledge Date: December 2023
Today Date: 14 Mar 2026

user

Bayyana yadda ake yin tuwon shinkafa.assistant

Shinkafa yin tuwon ni kano, kwa haka da yin tuwon shinkafa.

config.json:   0%|          | 0.00/890 [00:00<?, ?B/s]

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00002.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 1/2 [01:13<01:13, 73.96s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/1.46G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 2/2 [01:37<00:00, 48.84s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit:   0%|          | 0/2 [00:00<?, ?it/s]
Unsloth: Merging weights into 16bit:  50%|█████     | 1/2 [01:12<01:12, 72.73s/it]
Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [01:34<00:00, 47.27s/it]

Unsloth: Merge process complete. Saved to `/content/hausa_aligned_final`

✅ Alignment Complete. Model saved as 'hausa_aligned_final'